backend:
  name: github
  repo: gershom92/9t-kitchenware
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["kitchenware", "barware", "laundry", "hot_deals"] }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Selling Price (UGX)", name: "price", widget: "string" }
      - { label: "Original Price (UGX)", name: "old_price", widget: "string" }
      - { label: "Short Description", name: "description", widget: "string" }
      - { label: "Highlights", name: "highlights", widget: "list" }
